# Prepared Ubuntu 16.04 with stage2 bootstrapped
FROM awesomebytes/gentoo_prefix_ci_stage2

# Let's get some specs of the machine that is running this job
RUN cat /proc/cpuinfo && cat /proc/meminfo && df -h

# Bootstrap Gentoo Prefix
RUN STOP_BOOTSTRAP_AFTER=stage3 LATEST_TREE_YES=1 TESTING_PV=latest ./bootstrap-prefix.sh ${EPREFIX} noninteractive

ENTRYPOINT ["/bin/bash"]
