# Prepared Ubuntu 16.04 with stage1 bootstrapped
FROM awesomebytes/gentoo_prefix_ci_stage1

# Let's get some specs of the machine that is running this job
RUN cat /proc/cpuinfo
RUN cat /proc/meminfo
RUN df -h

# Bootstrap Gentoo Prefix
RUN LATEST_TREE_YES=1 TESTING_PV=latest ./bootstrap-prefix.sh ${EPREFIX} noninteractive stage2

ENTRYPOINT ["/bin/bash"]
