on:
  push

name: Gentoo Prefix CI

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: prepare
        run: |
          docker build -f bootstrap_stage/Dockerfile.prepare .

      - name: stage1
        run: |
          docker build -f bootstrap_stage/Dockerfile.stage1 .

      - name: stage2
        run: |
          docker build -f bootstrap_stage/Dockerfile.stage2 .

#      - name: stage3
#        run: |
#          docker build -f bootstrap_stage/Dockerfile.stage3 .

      - name: stage3
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bootstrap_stage/Dockerfile.stage3
          tags: prefix:stage3
          outputs: type=docker,dest=/tmp/prefix_stage3.tar

      - name: cache
        uses: actions/upload-artifact@v2
        with:
          name: prefix_stage3
          path: /tmp/prefix_stage3.tar

  emerge-system:
    needs: bootstrap
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: prepare
        run: |
          docker build -f bootstrap_stage/Dockerfile.prepare .

      - name: restore cache
        uses: actions/download-artifact@v2
        with:
          name: prefix_stage3
          path: /tmp

      - name: load image
        run: |
          docker load --input /tmp/prefix_stage3.tar
          docker image ls -a

      - name: emerge system
        run: |
          docker build -f bootstrap_stage/Dockerfile.emergesystem .
