on:
  push

name: Bootstrap Gentoo Prefix

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: prepare
        run: |
          docker build -f bootstrap_stage/Dockerfile.prepare .

      - name: stage1
        run: |
          docker build -f bootstrap_stage/Dockerfile.stage1 .

      - name: stage2
        run: |
          docker build -f bootstrap_stage/Dockerfile.stage2 .

#  stage1:
#    needs: prepare
#   runs-on: 

